### ISSUE TITLE
Shifted result gets camera rotated on X axis

### ISSUE THREAD

**Issue by schroef** [mrossini-ethz/camera-calibration-pvr#2] opened 2017-01-26 22:52 UTC
I tried the addon to day and tried following the little tutorial provided on main page. THough my result is completely different then what it should produce.

attached linke to blend file and some screen shots.
I tried rotating the camera on z axis after placement but doesnt help. Also started from scratch with no other mesh inside, didnt help

<img width="563" alt="screen shot 2017-01-26 at 6 47 05 pm" src="https://cloud.githubusercontent.com/assets/6923008/22353676/06fdeae2-e3f8-11e6-966a-56672e41b35e.png">
<img width="547" alt="screen shot 2017-01-26 at 6 46 59 pm" src="https://cloud.githubusercontent.com/assets/6923008/22353675/06fd152c-e3f8-11e6-8a61-6fdbe848412e.png">
[Camera match.blend.zip](https://github.com/mrossini-ethz/camera-calibration-pvr/files/733813/Camera.match.blend.zip)

**Comment by schroef** [comment] 2017-01-26 22:55
PS this is the output i see in the console

> Dangling edge: (2, 4)
> Dangling vertex: 4
> Attached vertex: 2
> [(0, 1), (1, 3), (2, 3), (0, 2)]
> Vertices: <Vector (2.9798, -0.9106)> <Vector (3.5440, -0.8582)> <Vector (3.5440, 0.3410)> <Vector (2.9798, 0.6143)> <Vector (2.9798, 0.6143)> <Vector (2.0393, 0.4678)>
> horizon <Vector (-2.7241, 0.0000)>
> vanish1 <Vector (5.6217, -0.6651)>
> vanish2 <Vector (-5.2338, -0.6651)>
> shift 0.06651302576065063
> focal 17.357690037871667
> A: [1.1688585569738088, -4.486442661050721, 6.473885185952914, -4.156156872543148, 1.0]
> B: [0.635022690548258, -2.906564825054971, 4.886401822917735, -3.6152939827132906, 1.0]
> P: [0.5338358664255508, -1.5798778359957502, 1.5874833630351786, -0.5408628898298575]
> Solutions:
> x: 1.0203428095566909
> Corner angles: [90.00009129693738, 89.9998795610731, 89.99992054220813, 90.00011178750489]
> Flatness: 4.484756441099648e-08 = 1.3093049038642421e-05 %
> Badness: 0.00041607421008373307
> Focal length: 17.357690037871667
> Camera Rx: -3.58953914427362e-05
> Camera Ry: -43.97633498302732
> Camera Rz: -4.362089744927408e-05
> Camera x: -1.1255760192871094
> Camera y: -0.08346723020076752
> Camera z: 0.29617422819137573
> Rectangle length: 0.34252956877068713
> Rectangle width: 0.24620065183743914
> Rectangle A: <Vector (-0.1713, -0.1231, 0.0000)>
> Rectangle B: <Vector (0.1713, -0.1231, -0.0000)>
> Rectangle C: <Vector (0.1713, 0.1231, 0.0000)>
> Rectangle D: <Vector (-0.1713, 0.1231, 0.0000)>

**Comment by schroef** [comment] 2017-01-26 23:00
However the mesh and the angles are correct. When i rotate it afterwards on X-axis all is fine.
<img width="1050" alt="screen shot 2017-01-26 at 7 02 27 pm" src="https://cloud.githubusercontent.com/assets/6923008/22354067/02c42d9a-e3fa-11e6-8a46-3b54ac9d8180.png">

**Comment by mrossini-ethz** [comment] 2017-01-27 07:06
Thank you shroef. I will investigate this.

**Comment by mrossini-ethz** [comment] 2017-01-27 11:55
I think I know what the problem is. You placed the vertices in camera view with a camera looking straight down. You should be using **Top Ortho** mode when doing that. It's in the documentation (except the Ortho part, which I will now add).
Apart from that, you need to be aware, that the rectangle will lie flat on the x-y-plane after calibration. You can fix that by clicking the **vertical** option after activating the calibration.

Can you verify that it works like that?

Correction: Ortho part _is_ in the documentation.

**Comment by mrossini-ethz** [comment] 2017-01-27 12:44
Ah, now I see! Apart from the problem mentioned above, there seems to be a separate issue. The reconstructed rectangle is placed at the cursor position, not at the origin. This is a bug! I will correct this.

**Comment by mrossini-ethz** [comment] 2017-01-27 13:26
It should be fixed now. Can you confirm?

**Comment by schroef** [comment] 2017-01-27 17:38
I tried 2 methods, one from camera view top mode ortho and the other
outside camera view in ortho mode. Both didn't work.

I did use 7 > 5 to go to top view and the. Ortho mode. But if you then go
to camera view your not in ortho view unless you set the Camera to ortho
mode.


Op vr 27 jan. 2017 om 09:26 schreef Marco Rossini <notifications@github.com>

**Comment by schroef** [comment] 2017-01-27 17:39
I tried 2 methods, one from camera view top mode ortho and the other outside camera view in ortho mode. Both didn't work. 

I did use 7 > 5 to go to top view and the. Ortho mode. But if you then go to camera view your not in ortho view unless you set the Camera to ortho mode.

**Comment by schroef** [comment] 2017-01-27 17:42
Isnt t bevaar i placed the camera vertical? I'll try and see what happens if I leave the camera horizontal

**Comment by mrossini-ethz** [comment] 2017-01-27 23:12
Does this mean you performed all the steps in the readme correctly? With the HEAD of the repository (latest version)? What orientation the camera starts with does not matter. The camera will be set to perspective mode. You should only place the vertices in top ortho mode. I am not quite sure what you are doing.

When I now open your .blend file, change to Top Ortho mode (Numpad 7, then Numpad 5) and move the vertices to the correct location and then press the _Shifted Perspective_ button, it works.

**Comment by schroef** [comment] 2017-01-28 04:40
Nope doesnt work for me, over tried it like 5 times. My is in the origin and mesh is moved to the location of the photo. 

What do you mean by move the vertices to the correct locations. Like my screengrab? Cause this aint working fro me on OSX
<img width="782" alt="screen shot 2017-01-28 at 12 37 24 am" src="https://cloud.githubusercontent.com/assets/6923008/22394283/33b104e8-e4f2-11e6-997e-3e84238ccf3e.png">

I'll check for the update aswell

**Comment by schroef** [comment] 2017-01-28 04:53
Update doesnt help neither, doesnt matter what i do. I always get the rotated view. Here's a screen grab

https://www.dropbox.com/s/scqux8u471dqsw5/Camera_calibration_v4.gif?dl=0

**Comment by mrossini-ethz** [comment] 2017-01-28 08:12
Ok, thank you schroef. This screen grab was very helpful. It seems to me, that you are doing everything right! We get the same result:

![vertical_orientation](https://cloud.githubusercontent.com/assets/5772838/22395299/867bfbdc-e539-11e6-9fd0-a7449566deec.png)

Just after you pressed the _Shifted Perspective_ button, you get the Operator Options in the Tool Shelf. Click _Vertical orientation_ and your _up_ direction will be changed. I pointed out above, that the rectangle will lie flat on the x-y-plane by default.

**Comment by schroef** [comment] 2017-01-28 20:40
A great! Yes that works perfect, not sure the size helps much. I just need to translate the camera and mesh up on Z-axis. I never see that window cause its always at the ultimate bottom due to all the tabs open. I hat the vertical tabs therefor.

What can the size do, cause the location of the Z-axis is wrong and therefor i cant really see the lining with the grid very well when im adjusting it.

**Comment by mrossini-ethz** [comment] 2017-01-29 08:02
The size determines the length of the reconstructed rectangle. I suggest you chose a size, then place the rectangle (together with the camera) wherever you want. You can also resize afterwards.

Thanks to your help you can now also place the cursor anywhere where you want the reconstructed rectangle, and when you hit _Shifted Perspective_, it will be placed there.

**Comment by mrossini-ethz** [comment] 2017-01-30 21:46
Can I close this?

**Comment by schroef** [comment] 2017-01-31 03:56
yes sir

**Comment by mrossini-ethz** [comment] 2017-01-31 07:36
Ok, thank you for the feedback!

**Closed as completed by mrossini-ethz** 2017-01-31 07:36 UTC
Labels: bug
